import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/common/Navigation";
import Footer from "@/components/common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vortex Running Club",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/vortex-b.jpg', sizes: '32x32' },
      { url: '/vortex-b.jpg', sizes: '192x192' },
      { url: '/vortex-b.jpg', sizes: '512x512' },
    ],
    apple: { url: '/vortex-b.jpg', sizes: '180x180' },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
